FROM node:8 AS node
FROM ruby:2.4

# 基本
ARG base_timezone="Asia/Tokyo"
ARG work_dir="/usr/local/share"
ARG DEBIAN_FRONTEND=noninteractive
# Node.js
ARG yarn_version="1.5.1"
# Rails
ARG rails_version="5.1.4"

# 基本 ###################################
RUN apt-get update
RUN apt-get -y install apt-utils --no-install-recommends

# locale設定
RUN apt-get -y install locales
RUN locale-gen ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LC_CTYPE ja_JP.UTF-8
RUN localedef -f UTF-8 -i ja_JP ja_JP.utf8

# timezone設定
ENV TZ="${base_timezone}"

# Rails ###################################
# Node.js multi-stage build
COPY --from=node /opt/yarn-v${yarn_version} /opt/yarn/
COPY --from=node /usr/local/bin/node /usr/local/bin/
RUN ln -s /opt/yarn/bin/yarn /usr/local/bin/yarn \
  && ln -s /opt/yarn/bin/yarn /usr/local/bin/yarnpkg

# Postgresで接続
RUN apt-get install -y postgresql-client --no-install-recommends
RUN rm -rf /var/lib/apt/lists/*

# Railsインストール
RUN gem install rails --version="~>${rails_version}"

# ポート解放
EXPOSE 3000
